#!/bin/bash

echo "=========================================="
echo "疫苗预约系统 - 启动脚本"
echo "=========================================="

BASE_DIR=$(cd "$(dirname "$0")" && pwd)

echo ""
echo "1. 启动 Redis (端口 6379)..."
redis-server --daemonize yes --port 6379

echo ""
echo "2. 启动第二个 Redis 实例 (端口 6380)..."
redis-server --daemonize yes --port 6380

echo ""
echo "3. 请确保以下服务已启动:"
echo "   - MySQL (端口 3306): test_ym_1, test_ym_2 数据库"
echo "   - Nacos (端口 8848): 注册中心"
echo "   - RabbitMQ (端口 5672): 消息队列"

echo ""
echo "4. 初始化数据库..."
echo "   请手动执行 sql/init.sql 脚本创建数据库和表"

echo ""
echo "=========================================="
echo "启动微服务 (请在新终端中执行)"
echo "=========================================="
echo ""
echo "后端服务启动顺序:"
echo "  cd $BASE_DIR && mvn clean install -DskipTests"
echo ""
echo "  # 启动网关"
echo "  java -jar yimiao-gateway/target/yimiao-gateway-1.0.0.jar"
echo ""
echo "  # 启动用户服务"
echo "  java -jar yimiao-user/target/yimiao-user-1.0.0.jar"
echo ""
echo "  # 启动疫苗服务"
echo "  java -jar yimiao-vaccine/target/yimiao-vaccine-1.0.0.jar"
echo ""
echo "  # 启动预约服务"
echo "  java -jar yimiao-appointment/target/yimiao-appointment-1.0.0.jar"
echo ""
echo "  # 启动支付服务"
echo "  java -jar yimiao-payment/target/yimiao-payment-1.0.0.jar"
echo ""
echo "  # 启动管理服务"
echo "  java -jar yimiao-admin/target/yimiao-admin-1.0.0.jar"
echo ""
echo "前端启动:"
echo "  cd $BASE_DIR/yimiao-frontend"
echo "  cnpm install"
echo "  cnpm run dev"
echo ""
echo "=========================================="
echo "服务端口说明"
echo "=========================================="
echo "网关服务:     9000"
echo "用户服务:     8083, 8084"
echo "疫苗服务:     8085, 8086"
echo "预约服务:     8087, 8088"
echo "支付服务:     8089, 8090"
echo "管理服务:     8081, 8082"
echo "前端:         3000"
echo "=========================================="
